package Interfaz;

import java.awt.Color;
import javax.swing.ImageIcon;

public class Jfrm_Presentacion1 extends javax.swing.JFrame {

    int xMouse, yMouse;
    
    public Jfrm_Presentacion1() {
        initComponents();
        this.setLocationRelativeTo(null);
        setIconImage(new ImageIcon(getClass().getResource("/Imagenes/Img_Icono1.jpg")).getImage()); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Jbtn_Tabla = new javax.swing.JButton();
        Jbtn_Juego = new javax.swing.JButton();
        Jbtn_Creditos = new javax.swing.JButton();
        jLabel = new javax.swing.JLabel();
        Header = new javax.swing.JPanel();
        Exit = new javax.swing.JPanel();
        Jlbl_Exit = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Colonna MT", 1, 76)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Porcentaje");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, -1, -1));

        Jbtn_Tabla.setBackground(new java.awt.Color(255, 255, 255));
        Jbtn_Tabla.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        Jbtn_Tabla.setText("Tabla");
        Jbtn_Tabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Jbtn_TablaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Jbtn_TablaMouseExited(evt);
            }
        });
        Jbtn_Tabla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jbtn_TablaActionPerformed(evt);
            }
        });
        jPanel1.add(Jbtn_Tabla, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 270, -1, -1));

        Jbtn_Juego.setBackground(new java.awt.Color(255, 255, 255));
        Jbtn_Juego.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        Jbtn_Juego.setText("Juego");
        Jbtn_Juego.setBorderPainted(false);
        Jbtn_Juego.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Jbtn_JuegoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Jbtn_JuegoMouseExited(evt);
            }
        });
        Jbtn_Juego.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jbtn_JuegoActionPerformed(evt);
            }
        });
        jPanel1.add(Jbtn_Juego, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 270, -1, -1));

        Jbtn_Creditos.setBackground(new java.awt.Color(255, 255, 255));
        Jbtn_Creditos.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        Jbtn_Creditos.setText("Creditos");
        Jbtn_Creditos.setBorderPainted(false);
        Jbtn_Creditos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Jbtn_CreditosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Jbtn_CreditosMouseExited(evt);
            }
        });
        Jbtn_Creditos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jbtn_CreditosActionPerformed(evt);
            }
        });
        jPanel1.add(Jbtn_Creditos, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 330, -1, -1));

        jLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Img_Fondo1.png"))); // NOI18N
        jPanel1.add(jLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        Header.setBackground(new java.awt.Color(255, 255, 255));
        Header.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                HeaderMouseDragged(evt);
            }
        });
        Header.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                HeaderMousePressed(evt);
            }
        });

        Exit.setBackground(new java.awt.Color(255, 255, 255));

        Jlbl_Exit.setFont(new java.awt.Font("Ravie", 1, 24)); // NOI18N
        Jlbl_Exit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Jlbl_Exit.setText("X");
        Jlbl_Exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Jlbl_Exit.setPreferredSize(new java.awt.Dimension(40, 40));
        Jlbl_Exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Jlbl_ExitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Jlbl_ExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Jlbl_ExitMouseExited(evt);
            }
        });

        javax.swing.GroupLayout ExitLayout = new javax.swing.GroupLayout(Exit);
        Exit.setLayout(ExitLayout);
        ExitLayout.setHorizontalGroup(
            ExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Jlbl_Exit, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
        );
        ExitLayout.setVerticalGroup(
            ExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ExitLayout.createSequentialGroup()
                .addComponent(Jlbl_Exit, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout HeaderLayout = new javax.swing.GroupLayout(Header);
        Header.setLayout(HeaderLayout);
        HeaderLayout.setHorizontalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderLayout.createSequentialGroup()
                .addComponent(Exit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 547, Short.MAX_VALUE))
        );
        HeaderLayout.setVerticalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderLayout.createSequentialGroup()
                .addComponent(Exit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(Header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void HeaderMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HeaderMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_HeaderMousePressed

    private void HeaderMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HeaderMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getXOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_HeaderMouseDragged

    private void Jlbl_ExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Jlbl_ExitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_Jlbl_ExitMouseClicked

    private void Jlbl_ExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Jlbl_ExitMouseEntered
        Exit.setBackground(Color.red);
        Jlbl_Exit.setBackground(Color.white);
    }//GEN-LAST:event_Jlbl_ExitMouseEntered

    private void Jlbl_ExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Jlbl_ExitMouseExited
        Exit.setBackground(Color.white);
        Jlbl_Exit.setBackground(Color.black);
    }//GEN-LAST:event_Jlbl_ExitMouseExited

    private void Jbtn_JuegoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jbtn_JuegoActionPerformed
        Jfrm_Juego juego = new Jfrm_Juego();
        juego.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Jbtn_JuegoActionPerformed

    private void Jbtn_TablaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jbtn_TablaActionPerformed
        Jfrm_Tabla tabla = new Jfrm_Tabla();
        tabla.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Jbtn_TablaActionPerformed

    private void Jbtn_TablaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Jbtn_TablaMouseExited
        Jbtn_Tabla.setBackground(Color.white);
        Jbtn_Tabla.setForeground(Color.black);
    }//GEN-LAST:event_Jbtn_TablaMouseExited

    private void Jbtn_TablaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Jbtn_TablaMouseEntered
        Jbtn_Tabla.setBackground(new Color(45,80,7));
        Jbtn_Tabla.setForeground(Color.white);
    }//GEN-LAST:event_Jbtn_TablaMouseEntered

    private void Jbtn_JuegoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Jbtn_JuegoMouseEntered
        Jbtn_Juego.setBackground(new Color(81,131,32));
        Jbtn_Juego.setForeground(Color.white);
    }//GEN-LAST:event_Jbtn_JuegoMouseEntered

    private void Jbtn_JuegoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Jbtn_JuegoMouseExited
        Jbtn_Juego.setBackground(Color.white);
        Jbtn_Juego.setForeground(Color.black);
    }//GEN-LAST:event_Jbtn_JuegoMouseExited

    private void Jbtn_CreditosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Jbtn_CreditosMouseEntered
        Jbtn_Creditos.setBackground(new Color(62,104,18));
        Jbtn_Creditos.setForeground(Color.white);
    }//GEN-LAST:event_Jbtn_CreditosMouseEntered

    private void Jbtn_CreditosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Jbtn_CreditosMouseExited
        Jbtn_Creditos.setBackground(Color.white);
        Jbtn_Creditos.setForeground(Color.black);
    }//GEN-LAST:event_Jbtn_CreditosMouseExited

    private void Jbtn_CreditosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jbtn_CreditosActionPerformed
        Jfrm_Creditos creditos = new Jfrm_Creditos();
        creditos.setVisible(true);
    }//GEN-LAST:event_Jbtn_CreditosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Jfrm_Presentacion1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Jfrm_Presentacion1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Jfrm_Presentacion1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Jfrm_Presentacion1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Jfrm_Presentacion1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Exit;
    private javax.swing.JPanel Header;
    private javax.swing.JButton Jbtn_Creditos;
    private javax.swing.JButton Jbtn_Juego;
    private javax.swing.JButton Jbtn_Tabla;
    private javax.swing.JLabel Jlbl_Exit;
    private javax.swing.JLabel jLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
